server:
  port: 5000

spring:
  application:
    name: java-web-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cynosdbmysql-grp-18qpvvko.sql.tencentcdb.com:28401/NGB?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: Ncscd!@#1990

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# Knife4j 配置
knife4j:
  enable: true
  openapi:
    title: Java Web API 文档
    description: 基于Spring Boot + MyBatis Plus的API接口文档
    version: 1.0.0
    concat: developer@example.com
  setting:
    language: zh_cn

logging:
  level:
    jfwang.api: debug
